CREATE DATABASE EJERCICIO04;
USE EJERCICIO04;

CREATE TABLE PUB(
	cod_pub INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  licencia VARCHAR(11) NOT NULL,
  domicilio VARCHAR(20),
  fechaApertura DATE NOT NULL,
  horario ENUM ("HOR1","HOR2","HOR3") NOT NULL,
  cod_titular VARCHAR(9) NOT NULL,
  cod_localidad INT NOT NULL
);

CREATE TABLE TITULAR(
	dni VARCHAR(9) PRIMARY KEY,
  nombre VARCHAR(20) NOT NULL,
  domicilio VARCHAR(50),
  cod_pub INT NOT NULL
);

CREATE TABLE EMPLEADO(
	dni VARCHAR(9) PRIMARY KEY,
  nombre VARCHAR(20) NOT NULL,
  domicilio VARCHAR(50)
);

CREATE TABLE  EXISTENCIAS(
  cod_articulo INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(20) NOT NULL,
  cantidad INT NOT NULL DEFAULT 0,
  pvp NUMERIC(5,2) NOT NULL CHECK (pvp > 0),
	cod_pub INT
);

CREATE TABLE LOCALIDAD(
	cod_localidad INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE PUB_EMPLEADO(
	cod_pub INT,
  dni_empleado VARCHAR(9),
  funcion ENUM ("LIMPIEZA", "SEGURIDAD", "CAMARERO"),  

  PRIMARY KEY (cod_pub, dni_empleado, funcion)
);

ALTER TABLE PUB
  ADD CONSTRAINT fk_PUB_LOCALIDAD_cd_localidad
    FOREIGN KEY (cod_localidad) REFERENCES LOCALIDAD(cod_localidad)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE TITULAR
  ADD CONSTRAINT  fk_TIT_PUB_cod_pub
    FOREIGN KEY (cod_pub) REFERENCES PUB(cod_pub)
    ON UPDATE CASCADE ON DELETE CASCADE,
  ADD tlf VARCHAR(9) NOT NULL;

ALTER TABLE EMPLEADO
  ADD tlf VARCHAR(9) NOT NULL;

ALTER TABLE EXISTENCIAS
  ADD CONSTRAINT  fk_EXI_PUB_cod_pub
    FOREIGN KEY (cod_pub) REFERENCES PUB(cod_pub)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE PUB_EMPLEADO
  ADD CONSTRAINT  fk_PEM_PUB_cod_pub
    FOREIGN KEY (cod_pub) REFERENCES PUB(cod_pub)
    ON UPDATE CASCADE ON DELETE CASCADE,  
  ADD CONSTRAINT  fk_PEM_EMPLEADO_dni_empleado
    FOREIGN KEY (dni_empleado) REFERENCES EMPLEADO(dni)
    ON UPDATE CASCADE ON DELETE CASCADE;



/* EDIT A FOREIGN KEY */
/*
ALTER TABLE TITULAR
  DROP FOREIGN KEY fk_TIT_PUB_cod_pub; 

ALTER TABLE TITULAR
    MODIFY COLUMN cod_pub INT NOT NULL,
    ADD CONSTRAINT fk_TIT_PUB_cod_pub 
    	FOREIGN KEY(cod_pub) REFERENCES PUB(cod_pub) 
      ON UPDATE CASCADE ON DELETE CASCADE;
*/