CREATE TABLE FABRICANTES(
  cd_fab INT auto_increment PRIMARY KEY,
  nombre VARCHAR(40) UNIQUE NOT NULL,
  direccion VARCHAR(50) NULL
);

CREATE TABLE TLF(
  tlf VARCHAR(20) PRIMARY KEY,
  cd_fab INT NOT NULL,

  CONSTRAINT fk_TLF_FAB_cd_fab
    FOREIGN KEY (cd_fab) REFERENCES FABRICANTES(cd_fab)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE MUEBLES(
  cd_fab INT NOT NULL,
  cd_mueble INT,
  linea VARCHAR(10) NULL,
  color VARCHAR(10) NULL,
  alto NUMERIC(5,2) NULL,
  profundidad NUMERIC(5,2) NULL,
  ancho NUMERIC(5,2) NULL,

  /* atributos de los subtipos */
  tipo ENUM ("Alto", "Encimera", "Bajo") NOT NULL,
  tipo_encimera VARCHAR(20) NULL,
  altura NUMERIC(5,2) NULL,

  PRIMARY KEY (cd_fab, cd_mueble),

  CONSTRAINT fk_MUE_FAB_cd_fab
    FOREIGN KEY (cd_fab) REFERENCES FABRICANTES(cd_fab)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE DISTRIBUIDORES(
  cd_dis INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) UNIQUE NOT NULL,
  domicilio VARCHAR(50) NOT NULL,
  tlf VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE TRABAJA(
  
)