CREATE TABLE USUARIOS(
	nif VARCHAR(9) PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  fechaNac DATE NOT NULL,
  titulacion VARCHAR(50)
);


CREATE TABLE WEB(
	cd_web INTEGER AUTO_INCREMENT PRIMARY KEY,
  url VARCHAR(60) NOT NULL UNIQUE,
  titulo VARCHAR(30) NOT NULL UNIQUE,
  tematica VARCHAR(20) NOT NULL,
  tipo ENUM("Wiki", "Blog", "Convencional") NOT NULL
);


CREATE TABLE CREAR(
  cd_web INTEGER,
  cd_usuario VARCHAR(9),

  PRIMARY KEY (cd_web, cd_usuario),

  CONSTRAINT fk_CRE_WEB_cd_web 
    FOREIGN KEY (cd_web) REFERENCES WEB(cd_web),
  CONSTRAINT fk_CRE_USUARIOS_nif
    FOREIGN KEY (cd_usuario) REFERENCES USUARIOS(nif)
);


CREATE TABLE WIKI(
  cd_web INTEGER PRIMARY KEY,
  n_entradas INTEGER NOT NULL DEFAULT 0,

  CONSTRAINT fk_WIK_WEB_cd_web
    FOREIGN KEY (cd_web) REFERENCES WEB(cd_web)
    ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE BLOG(
  cd_web INTEGER PRIMARY KEY,
  n_entradas INTEGER NOT NULL DEFAULT 0,
  n_etiquetas INTEGER NOT NULL DEFAULT 0,

  CONSTRAINT fk_BLO_WEB_cd_web
    FOREIGN KEY (cd_web) REFERENCES WEB(cd_web)
    ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IDIOMAS(
  cd_idioma INTEGER AUTO_INCREMENT PRIMARY KEY,
  descripcion VARCHAR(20) UNIQUE NOT NULL
);


CREATE TABLE HABLA(
  cd_web INTEGER,
  cd_idioma INTEGER,
  
  PRIMARY KEY (cd_web, cd_idioma),

  CONSTRAINT fk_HAB_WIKI_cd_web
    FOREIGN KEY (cd_web) REFERENCES WIKI(cd_web)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_HAB_IDIOMAS_cd_web
    FOREIGN KEY (cd_idioma) REFERENCES IDIOMAS(cd_idioma)
    ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE EMPRESA(
  cd_empresa INTEGER AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) UNIQUE NOT NULL,
  actividad VARCHAR(10) NULL
);


CREATE TABLE CONVENCIONAL(
  cd_web INTEGER PRIMARY KEY,
  n_entradas INTEGER NOT NULL DEFAULT 0,
  publicidad BOOLEAN NOT NULL DEFAULT false,
  marcos BOOLEAN NOT NULL DEFAULT false,

  CONSTRAINT fk_CON_WEB_cd_web
    FOREIGN KEY (cd_web) REFERENCES WEB(cd_web)
    ON DELETE CASCADE ON UPDATE CASCADE
);


