# SCRIP PARA GENERAR LA BASE DE DATOS NECESARIA PARA CREAR LA WEB
DROP DATABASE IF EXISTS papanoel;
CREATE DATABASE papanoel CHARACTER SET utf8mb4;
USE papanoel;

CREATE TABLE formulario(
  id INT AUTO_INCREMENT PRIMARY KEY,
  optn1 VARCHAR(50) NOT NULL,
  optn2 VARCHAR(50) NOT NULL,
  optn3 VARCHAR(50) NOT NULL,
  dinero ENUM('si', 'no') NOT NULL,
  color ENUM('azul', 'plata', 'rojo', 'negro') NOT NULL,
  email VARCHAR(50) NOT NULL,
  condiciones VARCHAR(50) DEFAULT 'NO ACEPTADAS' NOT NULL
);