public enum Ingredients {
  SAL, AZÚCAR, PIMIENTA, ORÉGANO, AJO, CÚRCUMA,

  LECHE, AGUA,

  TOMATE, PIMIENTO_ROJO, PIMIENTO_ITALIANO, PEPINO, CALABAZÍN,

  GUISANTES, LENTEJAS, ARROZ, ESPAGUETIS, MACARRONES,

  CHORIZO, JAMÓN, HUEVOS, SALCHICHAS, PECHUGA_DE_POLLO, SOLOMILLO,
}